version: "3.4"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: doctorcare-docker/docker-node-mongo-redis:v1
    volumes:
      - ./:/app # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
    environment: # phần này ta định nghĩa ở file .env nhé
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGOURL= mongodb://db/doctorcare
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      # - REDIS_PASSWORD=mypassword
      - PORT=${PORT}
   
    ports:
      - "${PORT}:${PORT}" # phần này ta định nghĩa ở file .env nhé
    command: yarn dev
    restart: always
    depends_on:
        - redis
        - db
  
  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: always
  
  redis:
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: always